#!/bin/sh
#
# Start the WiFi....
#

case "$1" in
  start)
	printf "Starting WiFi: "
	ifconfig wlan0 up
	sleep 2
	
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	ifconfig wlan0 down
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

